### ---Numpy---

### Task_1

In [10]:
import numpy as np

In [3]:
a = np.array([[1, 6], [2, 8], [3, 11], [3, 10], [1, 7]])

In [4]:
a.shape

(5, 2)

In [14]:
mean_a = np.mean(a, axis=0)
mean_a

array([2. , 8.4])

### Task_2

Variant_1

In [16]:
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

Variant_2

In [17]:
a_centered = np.subtract(a, mean_a)
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

### Task_3

In [25]:
a_centered_sp = a_centered.T[0] @ a_centered.T[1]
a_centered_sp

8.0

### Task_4**

In [29]:
np.cov(a.T)[0, 1]

2.0

### ---Pandas---

### Task_1

In [30]:
import pandas as pd

In [33]:
authors = pd.DataFrame({'author_id': [1, 2, 3],
                        'author_name': ['Тургенев', 'Чехов', 'Островский']}, columns=['author_id', 'author_name'])
authors

author_id author_name
0          1    Тургенев
1          2       Чехов
2          3  Островский

In [36]:
book = pd.DataFrame({'author_id': [1, 1, 1, 2, 2, 3, 3],
                    'book_title': ['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий',
                                   'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],
                    'price': [450, 300, 350, 500, 450, 370, 290]}, columns=['author_id', 'book_title', 'price'])
book

author_id            book_title  price
0          1           Отцы и дети    450
1          1                 Рудин    300
2          1     Дворянское гнездо    350
3          2      Толстый и тонкий    500
4          2       Дама с собачкой    450
5          3                 Гроза    370
6          3  Таланты и поклонники    290

### Task_2

In [41]:
authors_price = pd.merge(authors, book, on = 'author_id', how = 'inner')
authors_price

author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    450
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290

### Task_3

Variant_1

In [54]:
top5 = authors_price.sort_values(by='price').tail().reset_index(drop=True)
top5

author_id author_name         book_title  price
0          1    Тургенев  Дворянское гнездо    350
1          3  Островский              Гроза    370
2          1    Тургенев        Отцы и дети    450
3          2       Чехов    Дама с собачкой    450
4          2       Чехов   Толстый и тонкий    500

Variant_2

In [58]:
top5 = authors_price.nlargest(5, 'price').reset_index(drop=True)
top5

author_id author_name         book_title  price
0          2       Чехов   Толстый и тонкий    500
1          1    Тургенев        Отцы и дети    450
2          2       Чехов    Дама с собачкой    450
3          3  Островский              Гроза    370
4          1    Тургенев  Дворянское гнездо    350

### Task_4

In [80]:
price_min = authors_price.groupby('author_name').agg({'price': 'min'})
price_min = price_min.rename(columns={'price': 'min_price'})
price_min

min_price
author_name           
Островский         290
Тургенев           300
Чехов              450

In [84]:
price_max = authors_price.groupby('author_name').agg({'price': 'max'})
price_max = price_max.rename(columns={'price': 'max_price'})
price_max

max_price
author_name           
Островский         370
Тургенев           450
Чехов              500

In [83]:
price_mean = authors_price.groupby('author_name').agg({'price': 'mean'})
price_mean = price_mean.rename(columns={'price': 'mean_price'})
price_mean

mean_price
author_name            
Островский   330.000000
Тургенев     366.666667
Чехов        475.000000

In [89]:
authors_stat = pd.merge(price_min, price_max, on = 'author_name')
authors_stat = pd.merge(authors_stat, price_mean, on = 'author_name')
authors_stat

min_price  max_price  mean_price
author_name                                  
Островский         290        370  330.000000
Тургенев           300        450  366.666667
Чехов              450        500  475.000000

### Task_5**

In [92]:
authors_price['cover'] = ['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая']
authors_price

author_id author_name            book_title  price    cover
0          1    Тургенев           Отцы и дети    450  твердая
1          1    Тургенев                 Рудин    300   мягкая
2          1    Тургенев     Дворянское гнездо    350   мягкая
3          2       Чехов      Толстый и тонкий    500  твердая
4          2       Чехов       Дама с собачкой    450  твердая
5          3  Островский                 Гроза    370   мягкая
6          3  Островский  Таланты и поклонники    290   мягкая

In [93]:
?pd.pivot_table

In [95]:
book_info = pd.pivot_table(authors_price, values='price', index=['author_name'], columns=['cover'], aggfunc=np.sum)
book_info['мягкая'] = book_info['мягкая'].fillna(0)
book_info['твердая'] = book_info['твердая'].fillna(0)
book_info

cover        мягкая  твердая
author_name                 
Островский    660.0      NaN
Тургенев      650.0    450.0
Чехов           NaN    950.0

In [96]:
book_info.to_pickle('book_info.pkl')

In [97]:
book_info2 = pd.read_pickle('book_info.pkl')

In [98]:
book_info.equals(book_info2)

True